"""
Various JSON and text payloads generated by the Router API.
"""
sample_root = """Welcome to the Akanda appliance"""


sample_system_interface = (
    '{"interface": {"description": "", "media": "Ethernet autoselect '
    '(1000baseT full-duplex,master)", "mtu": 1500, "state": "up", '
    '"groups": ["egress"], "ifname": "ge1", "lladdr": "00:0c:29:e8:f9:2e", '
    '"addresses": ["fe80::20c:29ff:fee8:f92e/64", "192.168.229.129/24"]}}')


sample_system_interfaces = (
    '{"interfaces": [{"description": "", "media": "null", "mtu": 1500, '
    '"state": "down", "groups": ["enc"], "ifname": "ge0", "lladdr": "null", '
    '"addresses": []}, {"description": "", "media": "Ethernet autoselect '
    '(1000baseT full-duplex,master)", "mtu": 1500, "state": "up", '
    '"groups": ["egress"], "ifname": "ge1", "lladdr": "00:0c:29:e8:f9:2e", '
    '"addresses": ["fe80::20c:29ff:fee8:f92e/64", "192.168.229.129/24"]}, '
    '{"description": "", "media": "Ethernet autoselect (1000baseT '
    'full-duplex,master)", "mtu": 1500, "state": "up", "groups": [], '
    '"ifname": "ge2", "lladdr": "00:0c:29:e8:f9:38", "addresses": '
    '["192.168.57.101/24", "fe80::20c:29ff:fee8:f938/64"]}]}')
