#!/bin/sh
#

daemon="/usr/local/bin/akanda-metadata-proxy"
daemon_user=nobody
daemon_flags="/etc/metadata.conf"

. /etc/rc.d/rc.subr

rc_reload=NO
pexp="/usr/local/bin/python ${daemon} ${daemon_flags}"

rc_cmd $1
