#!/bin/sh
#
# $OpenBSD: sshd,v 1.1 2011/07/06 18:55:26 robert Exp $
# Akanda Custom config


daemon="/usr/sbin/sshd"

. /etc/rc.d/rc.subr

rc_pre() {
    /usr/local/bin/akanda-configure-ssh
}

rc_cmd $1
