#!/bin/bash
# this is an install script for nginx plus

# make nginx ssl dir
mkdir /etc/ssl/nginx
cp $(dirname $0)/../bin/* /etc/ssl/nginx/

wget https://cs.nginx.com/static/files/CA.crt -P /etc/ssl/nginx/
wget http://nginx.org/keys/nginx_signing.key -P /etc/ssl/nginx/

apt-key add nginx_signing.key

printf "deb https://plus-pkgs.nginx.com/debian `lsb_release -cs` nginx-plus\n" >/etc/apt/sources.list.d/nginx-plus.list

wget https://cs.nginx.com/static/files/90nginx -P /etc/apt/apt.conf.d

apt-get update

apt-get install nginx-plus -y
