#!/bin/bash -e
# Copyright (c) 2015 Akanda, Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
# This scripts preps apt with the nginx plus repo

# install required deps for this script
apt-get install lsb-release ca-certificates krb5-locales libsasl2-modules apt-utils apt-transport-https wget -y

# make nginx ssl dir
mkdir -p /etc/ssl/nginx
cp /tmp/in_target.d/nginx-repo.crt /etc/ssl/nginx/
cp /tmp/in_target.d/nginx-repo.key /etc/ssl/nginx/

wget https://cs.nginx.com/static/files/CA.crt -P /etc/ssl/nginx/
wget http://nginx.org/keys/nginx_signing.key -P /etc/ssl/nginx/

apt-key add /etc/ssl/nginx/nginx_signing.key

printf "deb https://plus-pkgs.nginx.com/debian `lsb_release -cs` nginx-plus\n" >/etc/apt/sources.list.d/nginx-plus.list

wget https://cs.nginx.com/static/files/90nginx -P /etc/apt/apt.conf.d

apt-get update
